Title: IBM When IBM Connections is integrated with Cognos users receive the error "AAA-SYS-0001 An internal error occurred" while testing dispatcher URI - United States

Text:
 TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 IBM Connections is integrated with Cognos. We then create a new namespace in Cognos configuration and restarting Cognos service. While testing the dispatcher URL we end up getting error "AAA-SYS-0001 An internal error occurred" after we enter user credentials. 

SYMPTOM
Error Message Screen shot attached. 

 Error message as seen in the cogserver.log file : 


CM-REQ-4342 An error occurred with the client. AAA-SYS-0001 An internal error occurred. xts.runjava.lang.RuntimeException: Expected a single account object java.lang.RuntimeException


CAUSE
Incorrect configuration of LDAP namespace in Cognos Configuration where authentication is Domino LDAP


ENVIRONMENT
Cognos BI 10 integrated with IBM Connections 



RESOLVING THE PROBLEM
To resolve the issue carryout the below steps: 


Change the following settings in the LDAP namespace in Cognos Configuration

1. Set " Use Bind credentials for search" to true

2. All the entries in the namespace configuration are case sensitive.
In Group Mapping, the object class should be mentioned as dominoGroup

3. In the bind user DN and password property enter the correct values(cn=user name , o= base distinguished name). The bind user is the one configured in Websphere and is also case sensitive.

4. Set the ObjectClass to organizationalUnit under Folder Mappings (Advanced)

5. Save the configuration changes and restart the Cognos Services for the changes to take effect.

You should now be able to login into Cognos via the dispatcher url

http:// <Server name / IP>: <port number>/cognos/servlet/dispatch


AAA-SYS-001Error.zip [/support/docview.wss?uid=swg21633144&aid=2]AAA-SYS-001Error.zip [/support/docview.wss?uid=swg21633144&aid=1]