Title: IBM After upgraded to ILMT v9.2.0.2, the import task failed with " ERROR: RuntimeError: Check lmtool: API connectivity failed" error. - United States

Text:
 TECHNOTE (FAQ)

QUESTION
 After upgraded to ILMT v9.2.0.2, the import task failed with " ERROR: RuntimeError: Check lmtool: API connectivity failed" error. 

CAUSE
The import log showed these errors:
# Logfile created on 2015-07-13 14:47:03 +0000 by logger.rb/v1.2.7 
2015-07-13 14:47:03 (+0:00:00.000) INFO: TEMA version: 9.2.0.2-20150626-1136 2015-07-13 14:47:03 (+0:00:00.000) INFO: Check datasources connectivity: Start .
.
.
2015-07-13 14:47:03 (+0:00:00.198) DEBUG: (0.000000s) SELECT DATAACCESSAUTH FROM SYSCAT.DBAUTH WHERE (GRANTEE = SESSION_USER) FETCH FIRST ROW ONLY 2015-07-13 14:47:03 (+0:00:00.002) DEBUG: (0.001000s) SELECT current_schema FROM "SYSIBM"."SYSDUMMY1" FETCH FIRST ROW ONLY 
2015-07-13 14:47:03 (+0:00:00.004) DEBUG: (0.003000s) SELECT VERSION FROM DBINFO FETCH FIRST ROW ONLY 
2015-07-13 14:47:03 (+0:00:00.012) DEBUG: (0.002000s) SELECT CREATIONTIME FROM LOCAL_OBJECT_DEFS WHERE (ID = 0) FETCH FIRST ROW ONLY 
2015-07-13 14:47:03 (+0:00:00.004) DEBUG: (0.001000s) select count (*) AS site_size from SITENAMEMAP where cast(UndecoratedSitename as varchar(256) for bit data) = 'IBM License Reporting' and IsDeleted = 0 
2015-07-13 14:47:04 (+0:00:00.257) ERROR: RuntimeError: Check lmtool: API connectivity failed. 
/var/app/ibm/LMT/wlp/usr/servers/server1/apps/tema.war/WEB-INF/l 
ib/etl/r unner.rb:168:in `check_datasources' 
/var/app/ibm/LMT/wlp/usr/servers/server1/apps/tema.war/WEB-INF/g 
ems/gems /sequel-4.14.0.89cbf5a1e987180e15ec99354762c3d9ee1d8acb 
/lib/sequel/datas et/actions.rb:137:in `each' 



ANSWER
This error will most likely happen when there are multiple datasource settings defined under Management | Data Sources 

 


[/support/docview.wss?uid=swg21962435&amp;aid=1]

There will always be one datasource setting initially as example shown below. There might be additional datasource settings required to connect to the existing IBM Endpoint Manager server(s) for a good reason. 

[/support/docview.wss?uid=swg21962435&aid=2] [/support/docview.wss?uid=swg21962435&aid=2]

To fix the issue, delete all additional datasource settings except the initial one. Manually run the import task again to verify if it works. If it does, then re-add the deleted datasource settings back one at the time. Then run the import task again each time a datasource setting is re-added. 

If it does not, delete the initial datasource setting and re-add it back again. Then run the import task again.